### ISSUE TITLE
Pomelo出现toobusy情况时，客户端尝试断开与服务器连接，出现卡死情况

### ISSUE THREAD

**Issue by readyuny** [laoyur/CCPomeloWrapper#1]
向服务器发送消息请求，但是可能由于服务器内存不足的情况出现了toobusy，此时客户端一直接收不到服务器的信息，在尝试断开连接的时候出现了卡死。不知道是什么问题导致，xcode没任何的错误提示。

**Comment by laoyur** [comment]
手动断开连接调用CCPomeloWrapper::stop()，内部实现在确实已连接的情况下，会调用libpomelo的pc_client_destroy(mClient);位置在CCPomeloWrapper.cpp的864行。楼主哥打断点看一下是否这个函数挂住了。如果是的话，应该是libpomelo自己的问题。

我也会尽快自己模拟一下这个case，看看如何绕过。
该场景应该等同于resp还没回来时，客户端主动调用stop()？

**Comment by readyuny** [comment]
是主动调用stop()的，然后一直卡着，过了心跳超时时间控制台就出现了pomelo心跳超时的提示，但程序依然卡着，我想应该是libpomelo自己的问题。

**Comment by readyuny** [comment]
后来发现只要客户端向服务器请求，服务器一旦出现问题不向客户端响应，libpomelo客户端过一段时间就出现”Pomelo client heartbeat timeout.“，然后程序卡死不动了，这次是没有调用stop()。

**Comment by laoyur** [comment]
这个问题我测出来了，但我不知道如何修正 o(>﹏<)o
重现步骤：以chat-of-pomelo-websocket为例，把chatHandler.js 中handler.send函数实现的最后三行注释掉，以模拟一个不完整的响应。

```
    next(null, {
        route: msg.route
    });
```

然后服务端主动关闭，客户端表示连接丢失，此时CCPomeloWrapper会自动调用stop()，即调用libpomelo的pc_client_destroy()函数，但这个函数会挂住，卡死主线程。

**Comment by readyuny** [comment]
能判断出是什么原因导致的连接丢失么？如果判断是服务器无响应导致的就不调用pc_client_destroy()方法。这样是否可行？

**Comment by laoyur** [comment]
我没有办法精确判断出这种状况，因为我对libpomelo内部的运作不熟悉，这个得官方来改了。
即便现在能判断出这种状况，不调用pc_client_destroy()方法也是行不通的，因为那样就内存泄露了。

我加了点修改，把pc_client_destroy()改成放到一个独立的线程中进行调用，程序没崩，主线程也得以解放了。但测试我上面提到的情况时，控制台中还是会打出类似如下的log：（当然，正常case中还是一切正常的）

```
chat-pomelo(34530,0xb0115000) malloc: *** error for object 0xabe35c0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
chat-pomelo(34530,0xb0115000) malloc: *** error for object 0xab1d160: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

```

不管怎样，总算现在能不耽误主线程的正常运作。楼主哥更新了代码试试。0.9.1

**Comment by readyuny** [comment]
好的，麻烦你了，我再去向官方提下问题，希望能得到解决。

**Comment by cynron** [comment]
能看一下具体卡在哪个调用上吗？是不是卡在pc_client_join这个调用上，能把卡的时候的主线程的backtrace打出来吗

**Comment by just4dream** [comment]
mark

**Comment by cynron** [comment]
@laoyur @readyuny  希望能给出卡住时候的backtrace

**Comment by laoyur** [comment]
我重新跟踪了一下，发现不是libpomelo的问题，是我封装得有问题，CCPomeloWrapper自身的实现导致了死锁。现在0.9.1的实现没有死锁问题了，但提示重复free，是因为调用pc_client_destroy()了两次。
我会尽快重新整理逻辑，修复这个问题。
真是应了论坛上某同学的说法：大部分问题都是使用者自己的问题，pomelo/libpomelo自身其实没问题  :)
希望CCPomeloWrapper能越来越完善 :)

**Comment by laoyur** [comment]
@readyuny 请测试一下0.9.2，如果还有问题我继续改

**Comment by readyuny** [comment]
嗯嗯，实在是麻烦你了。

**Comment by readyuny** [comment]
![snip20140303_1](https://f.cloud.github.com/assets/4201984/2310300/a06f1b20-a2e1-11e3-9c00-e6d9a753d4b0.png)
依然出现了程序卡死，求破啊！

**Comment by laoyur** [comment]
方便的话留个IM方式给我，直接沟通~

**Comment by laoyur** [comment]
哦，我知道了，这次不是死锁，是崩了，原因是cocos2dx-2.0分支下将NULL赋值给std::string导致的。我测的时候只测了cocos2dx-3.0，2.0的代码忘记改了，抱歉。你先将474行改成result.jsonMsg = json ? json : "";试一下，应该就可以了

**Comment by readyuny** [comment]
好的，我试试。不知道你有没有在Pomelo的交流群（292495320）里，叫灵夔的那个。
