### ISSUE TITLE
有一个小细节问一下

### ISSUE THREAD

**Issue by rangercyh** [laoyur/CCPomeloWrapper#3]
cpp文件里 CCPomeloImpl 的 stop 函数，第936行，主动去  remove 掉 disconnect 的消息，接着下一步就 destroy 掉这个 client，那么前面这个 remove 看起来就是不必要的了，因为 destroy 会把 client 注册的消息都删除掉，请帮我解答一下，谢谢

**Comment by laoyur** [comment]
如果不主动pc_remove_listener，直接pc_client_destroy的话，PC_EVENT_DISCONNECT事件还是会被libpomelo分发一次（大概是这样？细节我记不清了，手头也没有libpomelo的测试环境）。

这位哥们你是单纯为了看懂libpomelo，还是说使用CCPomeloWrapper过程中遇到实际问题了？

另外，预告一下，我已经开始着手封装libpomelo2，网易的人改动很大，封装起来有点费事。以后CCPomeloWrapper应该也不会再更新了，因为libpomelo已经死了。

**Comment by boyjunqiang** [comment]
支持！已暂停项目的网络部分 等待大神的新CCPomeloWrapper！

2014-10-31 10:05 GMT+08:00 laoyur notifications@github.com:

> 如果不主动pc_remove_listener，直接pc_client_destroy的话，PC_EVENT_DISCONNECT事件还是会被libpomelo分发一次（大概是这样？细节我记不清了，手头也没有libpomelo的测试环境）。
> 
> 这位哥们你是单纯为了看懂libpomelo，还是说使用CCPomeloWrapper过程中遇到实际问题了？
> 
> 另外，预告一下，我已经开始着手封装libpomelo2，网易的人改动很大，封装起来有点费事。以后CCPomeloWrapper应该也不会再更新了，因为libpomelo已经死了。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/laoyur/CCPomeloWrapper/issues/3#issuecomment-61204268
> .

## 

Wang Junqiang, PhD, CS
Add: Room 310, The 8th Student Dormitory of the Beijing University of Posts
and Telecommunications, No. 10, Xitucheng Road, Haidian District, Beijing,
China
Post: 100876
Mobile: +86 13693524886

**Comment by rick147** [comment]
Good job!

**Comment by rangercyh** [comment]
我在做一个我们游戏的libpomelo封装，参考你的代码了，所以问题比较细，嗯，我也准备看看libpomelo2
